create table "smm2_wiki"."courses" ("course_id" VARCHAR NOT NULL PRIMARY KEY,
  "course_name" VARCHAR,
  "course_type" VARCHAR,
  "course_image_url" VARCHAR,
  "course_detail_url" VARCHAR,
  "num_likes" BIGINT,
  "times_played" BIGINT,
  "clear_check_time" VARCHAR,
  "creator_name" VARCHAR,
  "creator_avatar" VARCHAR,
  "creator_nationality" VARCHAR,
  "tag1" VARCHAR,
  "tag2" VARCHAR,
  "wr_holder_name" VARCHAR,
  "wr_holder_avatar" VARCHAR,
  "wr_holder_nationality" VARCHAR,
  "wr_time" VARCHAR,
  "first_name" VARCHAR,
  "first_avatar" VARCHAR,
  "first_nationality" VARCHAR,
  "clear_rate" VARCHAR,
  "completed" BIGINT,
  "total_times" BIGINT,
  "is_poison" INTEGER,
  "oss_image_url" VARCHAR,
  "oss_image_detail_url" VARCHAR);
ALTER TABLE smm2_wiki.courses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE smm2_wiki.courses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
        

